server:
  port: 8090
  shutdown: graceful

spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:camunda;DB_CLOSE_DELAY=1000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    open-in-view: false

camunda:
  bpm:
    database:
      type: h2
      schema-update: create-drop
    job-execution:
      enabled: true
      deployment-aware: false
    admin-user:
      id: admin
      password: admin
    history-level: full
    history-level-default: full

logbook:
  exclude:
    - ${management.server.port}${management.endpoints.web.base-path}**
    - /camunda**
    - /engine-rest/**
  format.style: http
logging:
  level:
    org.zalando.logbook: TRACE

http.client:
  connect-timeout: 30s
  read-timeout: 30s
  write-timeout: 30s
  retry-attempt: 3
  retry-delay: 5s

clients:
  jsonplaceholder:
    prefix: "https://jsonplaceholder.typicode.com"
    post-by-id-uri: "${clients.jsonplaceholder.prefix}/posts/{id}"
    posts-uri: "${clients.jsonplaceholder.prefix}/posts"
